version: "3.8"

services:
  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DATABASE_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
    - 5432:5432
    volumes:
    - api-data:/var/lib/postgresql/data

volumes:
  api-data:
