version: "3.8"

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
    - 80:80
    volumes:
    - ./services/api/src:/src

  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DATABASE_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
    - 5432:5432
    volumes:
    - api-data:/var/lib/postgresql/data

  token_store:
    build:
      context: ./services/token_store
      dockerfile: Dockerfile
      args:
        TOKEN_STORE_PASSWORD: ${TOKEN_STORE_ADMIN_PASSWORD}
    ports:
    - 6379:6379

volumes:
  api-data:
