name: Build and Push Docker Images
on:
  push:
    branches:
     - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: services/api
          file: services/api/Dockerfile.prod
          tags: rvlzio/api.tasks.rvlz.io:${{github.ref_name}}
